### ISSUE TITLE
♻️ Expand `Error` type to report which step failed.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [lustre-labs/ssg#11]
We recently added an `Error` to lustre/ssg so folks can catch when their builds fail. This is great but the type is just a wrapper around `simplfile.FileError` which isn't all that helpful because its hard for the user to know where/how their build is failing.

It would be much better if we re-thought the error type to have variants for each step in the build.

**Comment by giacomocavalieri** [comment]
Looking at the build function maybe a possible error type could be something like this? Maybe the names could be better, but it's just to get an idea
```gleam
type BuildError {
  // When it first creates the temp directory
  CannotCreateTempDirectory(reason: simplifile.FileError)
  // When it tries to write all static assets into
  // the temp directory
  CannotWriteStaticAsset(reason: simplifile.FileError, path: String)
  // When it tries to generate a route
  CannotGenerateRoute(reason: simplifile.FileError, path: String, route: Route)
  // When it tries to copy the temp dir to the out dir
  CannotWriteToOutputDir(reason: simplifile.FileError)
  // When it tries to delete the temp dir as the last
  // build step
  CannotCleanupTempDir(reason: simplifile.FileError)
}
```
